# Generated by Django 4.2.9 on 2024-02-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryid', models.AutoField(db_column='CountryID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('isocode', models.CharField(db_column='ISOCode', max_length=50)),
                ('population', models.IntegerField(db_column='Population')),
                ('subregion', models.CharField(db_column='Subregion', max_length=50)),
            ],
            options={
                'db_table': 'Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Covid19Data',
            fields=[
                ('dataid', models.AutoField(db_column='DataID', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(db_column='Date')),
                ('confirmedcases', models.IntegerField(db_column='ConfirmedCases')),
                ('recoveredcases', models.IntegerField(db_column='RecoveredCases')),
                ('fatalities', models.IntegerField(db_column='Fatalities')),
            ],
            options={
                'db_table': 'COVID19Data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.AutoField(db_column='RegionID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'Region',
                'managed': False,
            },
        ),
    ]
