# Generated by Django 5.0.2 on 2024-03-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('state', models.CharField(db_column='State', max_length=45)),
                ('county', models.CharField(db_column='County', max_length=45)),
                ('confirmed', models.CharField(db_column='Confirmed', max_length=45)),
                ('deaths', models.CharField(db_column='Deaths', max_length=45)),
                ('recovered', models.CharField(db_column='Recovered', max_length=45)),
            ],
            options={
                'db_table': 'Cases',
                'managed': False,
            },
        ),
    ]
